name: Custom legal scan
description:  automate legal scan

on:
  repository_dispatch:

jobs:
  code_checkout:
    name: stage1
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install python dependencies
        shell: bash
        run: |
          python3 -m venv ${{ github.action_path }}/.venv
          source ${{ github.action_path }}/.venv/bin/activate
          pip3 install -r ${{github.action_path }}/requirements.txt

      - name: Run script
        shell: bash
        run: |
          source '${{ github.action_path }}/.venv/bin/activate'
          python3 ${{ github.action_path }}/main.py
