name: Workflow 3 - Process PR Details

on:
  repository_dispatch:

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process PR details
        run: |
          echo "Processing PR details:"
          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
          echo "PR Title: ${{ github.event.client_payload.pr_title }}"
          echo "PR URL: ${{ github.event.client_payload.pr_url }}"
