# .github/workflows/trigger-workflow.yml in clientRepo
name: Trigger LibraryRepo Workflow
on:
  push:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: OSrivalli/titus_multiplex/.github/workflows/a.yml@main
        with:
          message: “Triggered from clientRepo”
      - run: |
          echo "hello"
        
        
